GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
	"text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/delete/70e565ea6147v95jf0574124

###

GET http://localhost:3001/todo/complete/70e565ea6147v95jf0574124

###

PUT http://localhost:3001/todo/update/70e565ea6147v95jf0574124
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}
