GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
	"text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/delete/

###

GET http://localhost:3001/todo/complete/

###

PUT http://localhost:3001/todo/update/
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}